augmentation: false
balance_training_data: false
batch_size: 32
classes:
- cassava
- groundnut
- maize
- sweet_potatoes
- tobacco
model: xception
model_options:
  frozen_layers: 0
  input_shape: !!python/tuple
  - 299
  - 299
  - 3
  layer_sizes:
  - - 0.3
    - 256
  - - 0.3
    - 128
  - - 0.3
    - 64
  num_outputs: 5
  weights: null
name: baseline-small-no-other-xception-train
optimizer: SGD
optimizer_options: {}
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 40
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/test.yaml
training_steps: 500
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/train.yaml
validation_steps: null
verbose: 2
