augmentation: false
balance_training_data: false
batch_size: 32
class_mapping: false
classes:
- cassava
- groundnut
- maize
- tobacco
- other
model: xception
model_options:
  frozen_layers: 0
  input_shape: !!python/tuple
  - 299
  - 299
  - 3
  layer_sizes:
  - - 0.3
    - 10
  num_outputs: 5
  weights: null
name: all-no-sp/xception_l1_ls10_lr0.001_d0.3_fl0_test
optimizer: SGD
optimizer_options:
  lr: 0.001
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 40
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/train.yaml
training_steps: 300
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/test.yaml
validation_steps: null
verbose: 2
