- 
  path: /scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*
  prefixes:
  - m1
  - m2
  - m3
  - m4
  - m5
  - m6
  - m7
  - m9
  - m10
  - m11
  - m12
  - m13
  - m15
  - m16
  - m17
  - m18
  - m19
  - m20
  - m21
  - m22
  - m23
  - m24
  - m26
  - m27
  - m28
  - m30
  - m31
  - m32
  - m33
  - m34
  - m35
  - m36
  - m37
  - m38
  - m39
  - m40
- 
  path: /scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*
  prefixes:
  - m1
  - m2
  - m3
  - m4
  - m5
  - m6
  - m7
  - m9
  - m10
  - m11
  - m12
  - m13
  - m15
  - m16
  - m17
  - m18
  - m19
  - m20
  - m21
  - m22
  - m23
  - m24
  - m26
  - m27
  - m28
  - m30
  - m31
  - m32
  - m33
  - m34
  - m35
  - m36
  - m37
  - m38
  - m39
  - m40