augmentation: false
balance_training_data: true
batch_size: 32
classes:
- cassava
- groundnut
- maize
- other
- sweet_potatoes
- tobacco
model: xception
model_options:
  frozen_layers: 0
  input_shape: !!python/tuple
  - 299
  - 299
  - 3
  layer_sizes:
  - - 0.3
    - 512
  - - 0.3
    - 256
  - - 0.3
    - 64
  num_outputs: 6
  weights: null
name: baseline-bt-xception-3
optimizer: SGD
optimizer_options: {}
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 40
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/2.yaml
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/1.yaml
training_steps: 500
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/3.yaml
validation_steps: null
verbose: 2
