/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m1_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m2_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m3_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m4_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m5_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m6_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m7_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m9_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m10_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m11_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m12_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m13_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m15_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m16_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m17_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m18_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m19_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m20_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m21_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m22_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m23_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m24_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m26_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m27_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m28_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m30_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m31_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m32_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m33_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m34_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m35_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m36_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m37_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m38_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m39_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/original/*/m40_*.png

/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m1_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m2_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m3_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m4_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m5_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m6_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m7_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m9_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m10_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m11_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m12_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m13_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m15_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m16_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m17_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m18_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m19_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m20_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m21_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m22_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m23_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m24_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m26_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m27_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m28_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m30_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m31_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m32_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m33_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m34_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m35_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m36_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m37_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m38_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m39_*.png
/scratch-a/jmrziglod/sen2agri/data/malawi_summer/patches/augmented/*/m40_*.png