augmentation: false
balance_training_data: false
batch_size: 32
classes:
- cassava
- groundnut
- maize
- other
- sweet_potatoes
- tobacco
model: vgg16
model_options:
  frozen_layers: 15
  input_shape: !!python/tuple
  - 299
  - 299
  - 3
  layer_sizes:
  - - 0.3
    - 256
  - - 0.3
    - 128
  - - 0.3
    - 64
  num_outputs: 6
  weights: imagenet
name: baseline-small-vgg16-f15-1
optimizer: SGD
optimizer_options:
  lr: 0.005
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 40
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/2.yaml
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/3.yaml
training_steps: 500
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/1.yaml
validation_steps: null
verbose: 2
