augmentation: true
balance_training_data: false
batch_size: 32
class_mapping: false
classes:
- cassava
- maize
- other
- rice
model: vgg16
model_options:
  frozen_layers: 15
  input_shape: !!python/tuple
  - 224
  - 224
  - 3
  layer_sizes:
  - - 0.3
    - 60
  - - 0.3
    - 30
  num_outputs: 4
  weights: imagenet
name: paper-mozambique-augmented/vgg16_l2_ls60_lr0.0003_d0.3_fl15_test
optimizer: SGD
optimizer_options:
  lr: 0.0003
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 50
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/mozambique/artur/train.yaml
training_steps: 350
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/mozambique/artur/test.yaml
validation_steps: null
verbose: 2
