augmentation: false
balance_training_data: true
batch_size: 24
classes:
- cassava
- groundnut
- maize
- other
- sweet_potatoes
- tobacco
model: vgg16
model_options:
  frozen_layers: 15
  input_shape:
  - 299
  - 299
  - 3
  num_outputs: 6
name: c512-bb-ip-vgg16-f15-2
optimizer: RMSprop
optimizer_options:
  lr: 0.0005
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 40
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/1.yaml
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/3.yaml
training_steps: 1000
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/2.yaml
validation_steps: null
