augmentation: false
balance_training_data: false
batch_size: 32
class_mapping: false
classes:
- cassava
- groundnut
- maize
- tobacco
model: vgg16
model_options:
  frozen_layers: 0
  input_shape: !!python/tuple
  - 299
  - 299
  - 3
  layer_sizes:
  - - 0.5
    - 40
  - - 0.3
    - 20
  num_outputs: 4
  weights: null
name: no-other-no-sp/vgg16_l2_ls40_lr0.015_d0.5_fl0_train
optimizer: SGD
optimizer_options:
  lr: 0.015
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 40
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/test.yaml
training_steps: 300
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/train.yaml
validation_steps: null
verbose: 2
