augmentation: false
balance_training_data: false
batch_size: 32
class_mapping:
  cassava: crop
  groundnut: crop
  maize: crop
  other: non-crop
  sweet_potatoes: non-crop
  tobacco: crop
classes:
- crop
- non-crop
model: vgg16
model_options:
  frozen_layers: 7
  input_shape: !!python/tuple
  - 299
  - 299
  - 3
  layer_sizes:
  - - 0.3
    - 60
  - - 0.3
    - 30
  num_outputs: 2
  weights: imagenet
name: cropland/vgg16_l2_ls60_lr0.01_d0.3_fl7_train
optimizer: SGD
optimizer_options:
  lr: 0.01
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 50
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/malawi_summer/train_test_all_mosaics/test.txt
training_steps: 350
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/folds/malawi_summer/train_test_all_mosaics/train.txt
validation_steps: null
verbose: 2
