augmentation: false
balance_training_data: false
batch_size: 32
class_mapping:
  cassava: crop
  groundnut: crop
  maize: crop
  other: non-crop
  sweet_potatoes: crop
  tobacco: crop
classes:
- crop
- non-crop
model: vgg16
model_options:
  frozen_layers: 0
  input_shape: !!python/tuple
  - 299
  - 299
  - 3
  layer_sizes:
  - - 0.3
    - 10
  num_outputs: 2
  weights: null
name: binary-crop/vgg16_l1_ls10_lr0.015_d0.3_fl0_train
optimizer: SGD
optimizer_options:
  lr: 0.015
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 40
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/test.yaml
training_steps: 300
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/train.yaml
validation_steps: null
verbose: 2
