augmentation: false
balance_training_data: false
batch_size: 32
class_mapping:
  cassava: crop
  groundnut: crop
  maize: crop
  other: non-crop
  sweet_potatoes: crop
  tobacco: crop
classes:
- crop
- non-crop
model: xception
model_options:
  frozen_layers: 95
  input_shape: !!python/tuple
  - 299
  - 299
  - 3
  layer_sizes:
  - - 0.5
    - 20
  - - 0.3
    - 10
  num_outputs: 2
  weights: imagenet
name: binary-crop/xception_l2_ls20_lr0.001_d0.5_fl95_train
optimizer: SGD
optimizer_options:
  lr: 0.001
results_dir: /scratch-a/jmrziglod/sen2agri/results/
training_epochs: 40
training_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/test.yaml
training_steps: 300
validation_folds:
- /home/jmrziglod/projects/sen2agri/drone-crop-type/train_test_split/train.yaml
validation_steps: null
verbose: 2
